name: Helm
on:
  pull_request:
    paths:
      - 'hub/**.yaml'
      - '.github/workflows/Helm.yml'
  push:
    paths:
      - 'hub/**.yaml'
      - '.github/workflows/Helm.yml'

jobs:
  helm:
    name: Helm Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Helm
      run: |
        helm version
        helm repo add stable https://charts.helm.sh/stable
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
        helm plugin install https://github.com/jkroepke/helm-secrets --version v3.5.0
        helm repo update

    - name: Set K8s Context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1
      with:
        version: '3.6.1'


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: github-actions-role
        role-duration-seconds: 900

    - name: Test creds
      run: |
        aws sts get-caller-identity
        aws s3 ls terraform-hackweek-snowex

    - name: Helm list
      run: |
        helm list -A
