name: Terraform
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '!terraform/readme.md'
      - '.github/workflows/Terraform.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
      - '!terraform/readme.md'
      - '.github/workflows/Terraform.yml'

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: true
          activate-environment: true

      - name: Print conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install terragrunt
        shell: bash -l {0}
        run: |
          conda install --yes terragrunt

      - name: Configure AWS credentials
        id: aws-config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terragrunt Format
        id: fmt
        shell: bash -l {0}
        run: terragrunt run-all fmt -check --terragrunt-iam-role ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Terragrunt Init
        id: init
        shell: bash -l {0}
        run: terragrunt run-all init --terragrunt-iam-role ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Terragrunt Validate
        id: validate
        shell: bash -l {0}
        run: terragrunt run-all validate -no-color --terragrunt-iam-role ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Terragrunt Plan
        id: plan
        shell: bash -l {0}
        run: terragrunt run-all plan -no-color --terragrunt-iam-role ${{ secrets.AWS_ROLE_TO_ASSUME }}
        continue-on-error: true

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        shell: bash -l {0}
        run: terragrunt run-all apply -auto-approve --terragrunt-iam-role ${{ secrets.AWS_ROLE_TO_ASSUME }}